# .streamlit/secrets.toml

[connections.snowpark]
account = "anblicksorg_aws.us-east-1"
user = "SNOWDQ"
password = "SnowDQ@202308"
role = "SNOWDQ_ARL"
warehouse = "SNOWDQ_WH"
database = "SNOWDQ_DB"
schema = "PUBLIC"
client_session_keep_alive = true

[DQ_TABLE]
EXPECTATIONS = "SNOWDQ_DB.PUBLIC.DQ_RULES"
SUITE = "SNOWDQ_DB.PUBLIC.DQ_GROUP"
VALIDATION_RESULTS = "SNOWDQ_DB.PUBLIC.DQ_VALIDATION_RESULTS"
PROJECT = "SNOWDQ_DB.PUBLIC.DQ_PROJECT"
SUITE_RULE = "SNOWDQ_DB.PUBLIC.DQ_GROUP_RULE"